const path = require('path');
const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const { default: ImageminPlugin } = require('imagemin-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
const LicenseInfoWebpackPlugin = require('license-info-webpack-plugin').default;
const imageminMozjpeg = require('imagemin-mozjpeg');

const {
  entry,
  output,
  resolve,
  module: { rules },
  plugins,
  views,
  paths,
  imageMin,
} = require('./base');
const viewData = require(path.join(paths.view, '/data.json'));

const appendRules = [
  {
    test: /\.tsx?$/,
    exclude: /node_modules/,
    use: [
      {
        loader: 'awesome-typescript-loader',
        options: {
          configFileName: 'tsconfig.production.json',
        },
      },
    ],
  },
  {
    test: /\.css$/,
    use: ExtractTextPlugin.extract({
      fallback: 'style-loader',
      use: [
        {
          loader: 'css-loader',
          options: {
            importLoaders: 1,
            modules: true,
            localIdentName: '[name]__[local]--[hash:base64:5]',
          },
        },
        'postcss-loader',
      ],
    }),
  },
];

module.exports = {
  mode: 'production',
  entry,
  output,
  resolve,
  plugins: [
    ...plugins,
    new CopyWebpackPlugin([{ from: paths.assets }], {
      ignore: ['.DS_Store'],
    }),
    new ImageminPlugin({
      test: /.{jpg,gif,png}$/,
      optipng: null,
      jpegtran: null,
      gifsicle: imageMin.gif,
      pngquant: imageMin.png,
      plugins: [imageminMozjpeg(imageMin.jpg)],
    }),
    new ExtractTextPlugin('css/[name].css'),
    ...views.map(
      ({ template, filename }) =>
        new HtmlWebpackPlugin({
          template,
          filename: `${filename}.html`,
          inject: false,
          minify: {
            html5: true,
            includeAutoGeneratedTags: true,
            collapseWhitespace: true,
          },
          conf: Object.assign(
            { viewPath: paths.view, isProduction: true },
            viewData.common,
            viewData[filename] ? viewData[filename] : {},
          ),
        }),
    ),
    new LicenseInfoWebpackPlugin({
      glob: '{LICENSE,license,License}*',
    }),
  ],
  module: {
    rules: [...rules, ...appendRules],
  },
  optimization: {
    minimizer: [
      new UglifyJSPlugin({
        uglifyOptions: {
          output: { comments: /^\**!|@preserve|@license|@cc_on/ },
        },
      }),
    ],
  },
};
